name: Run Server Stats Script

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-server-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Give execution permission
        run: chmod +x server-stats.sh

      - name: Run Server Stats Script
        run: ./server-stats.sh
